# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_bigint', [dirname(__file__)])
        except ImportError:
            import _bigint
            return _bigint
        if fp is not None:
            try:
                _mod = imp.load_module('_bigint', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _bigint = swig_import_helper()
    del swig_import_helper
else:
    import _bigint
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _bigint.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _bigint.SwigPyIterator_value(self)
    def incr(self, n = 1): return _bigint.SwigPyIterator_incr(self, n)
    def decr(self, n = 1): return _bigint.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _bigint.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _bigint.SwigPyIterator_equal(self, *args)
    def copy(self): return _bigint.SwigPyIterator_copy(self)
    def next(self): return _bigint.SwigPyIterator_next(self)
    def __next__(self): return _bigint.SwigPyIterator___next__(self)
    def previous(self): return _bigint.SwigPyIterator_previous(self)
    def advance(self, *args): return _bigint.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _bigint.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _bigint.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _bigint.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _bigint.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _bigint.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _bigint.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _bigint.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class bigint(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, bigint, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, bigint, name)
    def __str__(self): return _bigint.bigint___str__(self)
    def __repr__(self): return _bigint.bigint___repr__(self)
    def toString(self): return _bigint.bigint_toString(self)
    def __init__(self, *args): 
        this = _bigint.new_bigint(*args)
        try: self.this.append(this)
        except: self.this = this
    def st(self): return _bigint.bigint_st(self)
    def read(self, *args): return _bigint.bigint_read(self, *args)
    def write(self, *args): return _bigint.bigint_write(self, *args)
    def readbin(self, *args): return _bigint.bigint_readbin(self, *args)
    def writebin(self, *args): return _bigint.bigint_writebin(self, *args)
    def __eq__(self, *args): return _bigint.bigint___eq__(self, *args)
    def __ne__(self, *args): return _bigint.bigint___ne__(self, *args)
    def __lt__(self, *args): return _bigint.bigint___lt__(self, *args)
    def __gt__(self, *args): return _bigint.bigint___gt__(self, *args)
    def __le__(self, *args): return _bigint.bigint___le__(self, *args)
    def __ge__(self, *args): return _bigint.bigint___ge__(self, *args)
    def __add__(self, *args): return _bigint.bigint___add__(self, *args)
    def __sub__(self, *args): return _bigint.bigint___sub__(self, *args)
    def __mul__(self, *args): return _bigint.bigint___mul__(self, *args)
    def __div__(self, *args): return _bigint.bigint___div__(self, *args)
    def __mod__(self, *args): return _bigint.bigint___mod__(self, *args)
    def __xor__(self, *args): return _bigint.bigint___xor__(self, *args)
    def powmod(self, *args): return _bigint.bigint_powmod(self, *args)
    def __iadd__(self, *args): return _bigint.bigint___iadd__(self, *args)
    def __isub__(self, *args): return _bigint.bigint___isub__(self, *args)
    def __imul__(self, *args): return _bigint.bigint___imul__(self, *args)
    def __idiv__(self, *args): return _bigint.bigint___idiv__(self, *args)
    def __imod__(self, *args): return _bigint.bigint___imod__(self, *args)
    def __ixor__(self, *args): return _bigint.bigint___ixor__(self, *args)
    def __neg__(self): return _bigint.bigint___neg__(self)
    __swig_destroy__ = _bigint.delete_bigint
    __del__ = lambda self : None;
bigint_swigregister = _bigint.bigint_swigregister
bigint_swigregister(bigint)

def _out(*args):
  return _bigint._out(*args)
_out = _bigint._out

def _in(*args):
  return _bigint._in(*args)
_in = _bigint._in

# This file is compatible with both classic and new-style classes.


